# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Clarity & Hypertext
tagline:          'Brian Christiansen | UX and Instructional Designer' #Site Title Tag
description:      'The Weblog and Portfolio of Brian Christiansen'
url:              http://briandigital.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Brian Christiansen'
  url:            https://twitter.com/briandigital

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# collections:
#   portfolio:
#     permalink: "/:collection/:path/"
#     output: "true"

defaults:
# -
#   scope:
#     path: ""
#     type: "portfolio" # a collection in your site, in plural form
#   values:
#     layout: "page"
-
  scope:
    path: "_posts"
    type: "posts" # a collection in your site, in plural form
  values:
      layout: "post"
      
# Custom vars
version:            3.5.3
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/briandigital/briandigital4

twitter_username:   https://twitter.com/briandigital